### ISSUE TITLE
forrest of lost path broken?

### ISSUE THREAD

**Issue by lenicus101** [amaryllisninja/python_text_rpg#10]
so was reading the map excel file trying to guide myself to the end path of Forrest but it seems either map is wrong of forrest is broken... or im dumb.... 

What do you do?
go s
You go South.
After moving, you are now in Entrance to the Forest of the Lost.
Entrance to the Forest of the Lost
You find yourself at the entrance to a deep, dark forest. Peering inside, you can see
that the light is almost non-existant. The path seems to disappear into the forest.
To the South is the Forest of the Lost. To the North is a wooded path.
There is 1 dusty bread, here.
There is 1 fairy, here.
There is 1 dead skeleton, here.

You take the dusty bread.
loot skeleton
On skeleton, you found:

You have killed Fairy.
loot fairy

What do you do?
go s
You go South.

What do you do?
go e
You go East.

What do you do?
go s
You go South.

What do you do?
go s
You go South.

What do you do?
go s
You go South.

What do you do?
go s
You go South.

What do you do?
go e
You go East.

What do you do?
go e
You go East.

What do you do?
go e

What do you do?
go s
You go South.

What do you do?
go s
You go South.

What do you do?
go w
You go West.

What do you do?
go n
You go North.

What do you do?
go w
You go West.

What do you do?
go w
You go West.

What do you do?
go w
You go West.

What do you do?
go s
You cannot go that way.

according to the excel map i should be in tile 68 and able to go south to continue the path... 

What do you do?

**Comment by amaryllisninja** [comment]
Room 69 had been linked to room 69 to the W, instead of 68. Issue fixed. Next push will have fixed code.
