### ISSUE TITLE
Combat health bug

### ISSUE THREAD

**Issue by lenicus101** [amaryllisninja/python_text_rpg#7]
What do you do?
use healing potion
potion
You consume the healing potion.

**Your health is now 14.**

What do you do?
attack fairy
You are engaged in combat with Fairy.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 5 points of damage!
Fairy has died.
You have killed Fairy.

What do you do?
loot fairy
On fairy, you found:
dagger
mana potion

What do you do?
go s
You go South.
After moving, you are now in Forest of the Lost.
Forest of the Lost
You find yourself surrounded by trees, vines, and brambles. You can't tell from which
way you came or which way you should go. There is barely any light and you have lost any signs of a path.
You are hopelessly lost.
There is 1 goblin, here.

What do you do?
attack goblin
You are engaged in combat with Goblin.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 missed.
Goblin is unharmed.
**Goblin missed.
You are down to 9 health points.**
You have cuts and bruises everywhere. You do not feel good.

**Comment by lenicus101** [comment]
What do you do?
eat dusty bread
food
You consume the dusty bread.

Your health is now 3.

What do you do?
look around

What do you do?
attack 
Attack what?

What do you do?
?
That's not a command I recognize.

You can't blame this one on your dad.

What do you do?
attack giant snake
You are engaged in combat with Giant Snake.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 5 points of damage!
Giant Snake has cuts and bruises everywhere.
Giant Snake hit for 1 points of damage!
You are down to 0 health points.

**Comment by amaryllisninja** [comment]
Is this issue the same as reported in Issue #9 ? If so, I will close this issue and only update to Issue #9.

**Comment by amaryllisninja** [comment]
"Healing outside battle doesnt seem to registered
So I could be at full hp but if I start a new combat, it goes to what my hp was at the end of the last combat"

**Comment by amaryllisninja** [comment]
Issue has been fixed. Next push will have update.
