### ISSUE TITLE
use an item, it does nothing, but gets removed anyways.

### ISSUE THREAD

**Issue by lenicus101** [amaryllisninja/python_text_rpg#8]
What do you do?
loot larger spider
On larger spider, you found:
silken thread

What do you do?
use silken thread
item

What do you do?
look at inventory
In your inventory, you have:
lock picking kit
rope
water
water
water
water
water
water
You have 104 gold.

What do you do?

**Comment by amaryllisninja** [comment]
This is a bug that will be fixed when further item functionality is scripted. Thank you for reporting the issue.
