### ISSUE TITLE
combat hp calculations are wrong

### ISSUE THREAD

**Issue by lenicus101** [amaryllisninja/python_text_rpg#9]
i was in the forrest of the lost, finished killing one skeleton and was off to attack another... 

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 1 points of damage!
Skeleton is covered with lacerations and blood.
Skeleton hit for 2 points of damage!
You are down to 17 health points.
You have a few scrapes. You feel fine.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 3 points of damage!
Skeleton has died.
You have killed Skeleton.

What do you do?
loot skeleton
On skeleton, you found:
short sword

What do you do?
attack skeleton
You are engaged in combat with Skeleton.

Do you ATTACK, use an ITEM, or FLEE?  item 
That's not a valid option. Please choose 'attack', 'item', or 'flee'.

Do you ATTACK, use an ITEM, or FLEE?  item
lock picking kit
rope
healing potion
healing potion
healing potion
healing potion
healing potion
short sword
Which item in your inventory do you use? (Or CANCEL)
healing potion
potion
You consume the healing potion.

**Your health is now 20.
Skeleton missed.
You are down to 17 health points.
You have a few scrapes. You feel fine.**

Do you ATTACK, use an ITEM, or FLEE?  item
lock picking kit
rope
healing potion
healing potion
healing potion
healing potion
short sword
Which item in your inventory do you use? (Or CANCEL)
healing potion
potion
You consume the healing potion.

**Your health is now 18.
Skeleton hit for 2 points of damage!
You are down to 15 health points.
You have cuts and bruises everywhere. You do not feel good.**

Do you ATTACK, use an ITEM, or FLEE?  item
lock picking kit
rope
healing potion
healing potion
healing potion
short sword
Which item in your inventory do you use? (Or CANCEL)
healing potion
potion
You consume the healing potion.

**Your health is now 20.
Skeleton hit for 1 points of damage!
You are down to 16 health points.
You have a few scrapes. You feel fine.**

Do you ATTACK, use an ITEM, or FLEE?  item healing potion
That's not a valid option. Please choose 'attack', 'item', or 'flee'.

Do you ATTACK, use an ITEM, or FLEE?  item
lock picking kit
rope
healing potion
healing potion
short sword
Which item in your inventory do you use? (Or CANCEL)
healing potion
potion
You consume the healing potion.

**Your health is now 18.
Skeleton hit for 1 points of damage!
You are down to 16 health points.
You have a few scrapes. You feel fine.**

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 3 points of damage!
Skeleton has a few scrapes.
Skeleton hit for 5 points of damage!
You are down to 11 health points.
You have cuts and bruises everywhere. You do not feel good.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 2 points of damage!
Skeleton has a few scrapes.
Skeleton hit for 1 points of damage!
You are down to 10 health points.
You have cuts and bruises everywhere. You do not feel good.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 3 points of damage!
Skeleton has a few scrapes.
Skeleton missed.
You are down to 10 health points.
You have cuts and bruises everywhere. You do not feel good.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 1 points of damage!
Skeleton has a few scrapes.
Skeleton missed.
You are down to 10 health points.
You have cuts and bruises everywhere. You do not feel good.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 1 points of damage!
Skeleton has a few scrapes.
Skeleton missed.
You are down to 10 health points.
You have cuts and bruises everywhere. You do not feel good.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 5 points of damage!
Skeleton has cuts and bruises everywhere.
Skeleton hit for 5 points of damage!
You are down to 5 health points.
You are covered with lacerations and blood. You feel awful.

Do you ATTACK, use an ITEM, or FLEE?  item
lock picking kit
rope
healing potion
short sword
Which item in your inventory do you use? (Or CANCEL)
healing potion
potion
You consume the healing potion.

**Your health is now 22.
Skeleton hit for 4 points of damage!
You are down to 13 health points.**
You have cuts and bruises everywhere. You do not feel good.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 4 points of damage!
Skeleton is covered with lacerations and blood.
Skeleton hit for 6 points of damage!
You are down to 7 health points.
You are covered with lacerations and blood. You feel awful.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 4 points of damage!
Skeleton is covered with lacerations and blood.
Skeleton missed.
You are down to 7 health points.
You are covered with lacerations and blood. You feel awful.

Do you ATTACK, use an ITEM, or FLEE?  attack
God2 hit for 1 points of damage!
Skeleton has died.
You have killed Skeleton.

**Comment by amaryllisninja** [comment]
This looks an issue that I also ran across and fixed. Are you using the version of the game I pushed today?

**Comment by amaryllisninja** [comment]
"As where with issue 9, I am healing in combat and the damage calculations are off... seem the damage being healed vs done."

**Comment by amaryllisninja** [comment]
Issue has been fixed. Fix to be pushed in next update.
